### ISSUE TITLE
General SDK Status: is alloy-codeless-lite-ios ready for use in production apps as is?

### ISSUE THREAD

**Issue by DBCintron** [UseAlloy/alloy-codeless-lite-ios#16]
Hi Alloy Team,

Our team wanted to check in to see whether this repo is considered done/ready for use? We saw that there's still some active development work ongoing so we wanted to get a sense of whether:
1. This is considered completely ready to go 👍 
2. This is considered a work in progress, and we can make use of it but should expect to need to do some configuration to get it working
3. This is considered an early work in progress and we potentially shouldn't consider it ready for use

Our team actually has a React Native app so we're considering making this SDK as well as its Android version available to our app using Expo Modules API as we've done previously for other native SDKs https://docs.expo.dev/modules/overview/. We'd also like to know whether you've advised past customers on integrating within React Native or if you have any alternate suggestions?

Thanks!

**Comment by mrestuccia** [comment]
@DBCintron Alloy connected directly with you. Yes. It's ready.
Happy to discuss details once you get to the integration phase.
