### ISSUE TITLE
Can we lower the minimum deployment target?

### ISSUE THREAD

**Issue by heeyunlee** [UseAlloy/alloy-codeless-lite-ios#19]
Our team is trying to integrate Alloy into our app by using this iOS Alloy SDK, but our app's current minimum iOS deployment target is iOS `12.0`, while this SDK's minimum iOS deployment target is iOS `16.0`. Upgrading our minimum deployment target from `12.0` to `16.0` would have a quite drastic impact on our users, and we are hoping to find a solution that requires less drastic change. 
- Q1: Is there any particular reason you set the minimum deployment target to `16.0`?
- Q2: If not, can we lower it to `15.0`? After [forking the repo](https://github.com/heeyunlee/alloy-codeless-lite-ios) and doing some manual tests, I found that it is possible without making any changes to the source material.

**Comment by mrestuccia** [comment]
@heeyunlee we are considering lowering to 15, will keep you posted. 
Are you working this integration for a particular company?

**Comment by heeyunlee** [comment]
Great! I work at a fintech based in NYC called dub. I think our team has been in contact with the Alloy team for some time. If you guys are open to it, I also don't mind creating a PR to lower the minimum deployment target to `15.0` myself.

**Comment by mrestuccia** [comment]
@heeyunlee feel free to put a PR.

**Comment by mrestuccia** [comment]
@heeyunlee closing with the new release.
