### ISSUE TITLE
Iovation Device Risk Integration

### ISSUE THREAD

**Issue by spencer-hivert** [UseAlloy/alloy-codeless-lite-ios#22]
Hi there 👋 

We've already integrated the [Web SDK](https://developer.alloy.com/public/docs/document-verification-web-sdk) with the [TruValidate (Iovation) Device Risk Integration](https://developer.alloy.com/public/docs/truvalidate-device-risk-integration).

I'm looking to leverage this on iOS as well, but the `iovation_blackbox` field doesn't appear to be available in the [`AuthInitResponse.swift`](https://github.com/UseAlloy/alloy-codeless-lite-ios/blob/main/Sources/alloy-codeless-lite-ios/Internal/Network/Endpoints/Model/AuthInitResponse.swift)

If it's as easy as modifying the response to include this field, I'd be happy to take it myself, but looking for a little guidance before proceeding!

**Comment by borisonr** [comment]
Hi Spencer, thanks for the question!
We don't have an implementation for TruValidate/Iovation Device Risk on the iOS package at the moment. If you are looking for this to be added, would you mind going through our regular channels for client requests?
